[project]
name = "healthcheck_service"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.20.0.post0",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.0",
]
